// 자동 생성 파일 — scripts/build-frame-manifest.mjs 로 갱신한다. 직접 수정하지 마세요.
/* eslint-disable */
export const frameSets = {
  "cleaning-identity": [
    require("../../assets/formi/cleaning-identity-f0.png"),
    require("../../assets/formi/cleaning-identity-f1.png"),
    require("../../assets/formi/cleaning-identity-f2.png"),
    require("../../assets/formi/cleaning-identity-f3.png"),
  ],
  "cleaning-master": [
    require("../../assets/formi/cleaning-master-f0.png"),
    require("../../assets/formi/cleaning-master-f1.png"),
    require("../../assets/formi/cleaning-master-f2.png"),
    require("../../assets/formi/cleaning-master-f3.png"),
  ],
  "cleaning-sprout": [
    require("../../assets/formi/cleaning-sprout-f0.png"),
    require("../../assets/formi/cleaning-sprout-f1.png"),
    require("../../assets/formi/cleaning-sprout-f2.png"),
    require("../../assets/formi/cleaning-sprout-f3.png"),
    require("../../assets/formi/cleaning-sprout-f4.png"),
    require("../../assets/formi/cleaning-sprout-f5.png"),
    require("../../assets/formi/cleaning-sprout-f6.png"),
    require("../../assets/formi/cleaning-sprout-f7.png"),
  ],
  "exercise-identity": [
    require("../../assets/formi/exercise-identity-f0.png"),
    require("../../assets/formi/exercise-identity-f1.png"),
    require("../../assets/formi/exercise-identity-f2.png"),
    require("../../assets/formi/exercise-identity-f3.png"),
    require("../../assets/formi/exercise-identity-f4.png"),
    require("../../assets/formi/exercise-identity-f5.png"),
  ],
  "exercise-master": [
    require("../../assets/formi/exercise-master-f0.png"),
    require("../../assets/formi/exercise-master-f1.png"),
    require("../../assets/formi/exercise-master-f2.png"),
    require("../../assets/formi/exercise-master-f3.png"),
  ],
  "exercise-sprout": [
    require("../../assets/formi/exercise-sprout-f0.png"),
    require("../../assets/formi/exercise-sprout-f1.png"),
    require("../../assets/formi/exercise-sprout-f2.png"),
    require("../../assets/formi/exercise-sprout-f3.png"),
  ],
  "meal-identity": [
    require("../../assets/formi/meal-identity-f0.png"),
    require("../../assets/formi/meal-identity-f1.png"),
    require("../../assets/formi/meal-identity-f2.png"),
    require("../../assets/formi/meal-identity-f3.png"),
  ],
  "meal-master": [
    require("../../assets/formi/meal-master-f0.png"),
    require("../../assets/formi/meal-master-f1.png"),
    require("../../assets/formi/meal-master-f2.png"),
    require("../../assets/formi/meal-master-f3.png"),
    require("../../assets/formi/meal-master-f4.png"),
    require("../../assets/formi/meal-master-f5.png"),
    require("../../assets/formi/meal-master-f6.png"),
    require("../../assets/formi/meal-master-f7.png"),
  ],
  "meal-sprout": [
    require("../../assets/formi/meal-sprout-f0.png"),
    require("../../assets/formi/meal-sprout-f1.png"),
    require("../../assets/formi/meal-sprout-f2.png"),
    require("../../assets/formi/meal-sprout-f3.png"),
    require("../../assets/formi/meal-sprout-f4.png"),
    require("../../assets/formi/meal-sprout-f5.png"),
    require("../../assets/formi/meal-sprout-f6.png"),
    require("../../assets/formi/meal-sprout-f7.png"),
  ],
  "reading-identity": [
    require("../../assets/formi/reading-identity-f0.png"),
    require("../../assets/formi/reading-identity-f1.png"),
    require("../../assets/formi/reading-identity-f2.png"),
    require("../../assets/formi/reading-identity-f3.png"),
    require("../../assets/formi/reading-identity-f4.png"),
  ],
  "reading-master": [
    require("../../assets/formi/reading-master-f0.png"),
    require("../../assets/formi/reading-master-f1.png"),
    require("../../assets/formi/reading-master-f2.png"),
    require("../../assets/formi/reading-master-f3.png"),
    require("../../assets/formi/reading-master-f4.png"),
    require("../../assets/formi/reading-master-f5.png"),
  ],
  "reading-sprout": [
    require("../../assets/formi/reading-sprout-f0.png"),
    require("../../assets/formi/reading-sprout-f1.png"),
    require("../../assets/formi/reading-sprout-f2.png"),
    require("../../assets/formi/reading-sprout-f3.png"),
    require("../../assets/formi/reading-sprout-f4.png"),
    require("../../assets/formi/reading-sprout-f5.png"),
  ],
  "seed": [
    require("../../assets/formi/seed-f0.png"),
    require("../../assets/formi/seed-f1.png"),
    require("../../assets/formi/seed-f2.png"),
    require("../../assets/formi/seed-f3.png"),
    require("../../assets/formi/seed-f4.png"),
  ],
  "selfcare-identity": [
    require("../../assets/formi/selfcare-identity-f0.png"),
    require("../../assets/formi/selfcare-identity-f1.png"),
    require("../../assets/formi/selfcare-identity-f2.png"),
    require("../../assets/formi/selfcare-identity-f3.png"),
  ],
  "selfcare-master": [
    require("../../assets/formi/selfcare-master-f0.png"),
    require("../../assets/formi/selfcare-master-f1.png"),
    require("../../assets/formi/selfcare-master-f2.png"),
    require("../../assets/formi/selfcare-master-f3.png"),
    require("../../assets/formi/selfcare-master-f4.png"),
    require("../../assets/formi/selfcare-master-f5.png"),
    require("../../assets/formi/selfcare-master-f6.png"),
    require("../../assets/formi/selfcare-master-f7.png"),
  ],
  "selfcare-sprout": [
    require("../../assets/formi/selfcare-sprout-f0.png"),
    require("../../assets/formi/selfcare-sprout-f1.png"),
    require("../../assets/formi/selfcare-sprout-f2.png"),
    require("../../assets/formi/selfcare-sprout-f3.png"),
  ],
  "study-identity": [
    require("../../assets/formi/study-identity-f0.png"),
    require("../../assets/formi/study-identity-f1.png"),
    require("../../assets/formi/study-identity-f2.png"),
    require("../../assets/formi/study-identity-f3.png"),
    require("../../assets/formi/study-identity-f4.png"),
    require("../../assets/formi/study-identity-f5.png"),
    require("../../assets/formi/study-identity-f6.png"),
    require("../../assets/formi/study-identity-f7.png"),
  ],
  "study-master": [
    require("../../assets/formi/study-master-f0.png"),
    require("../../assets/formi/study-master-f1.png"),
    require("../../assets/formi/study-master-f2.png"),
    require("../../assets/formi/study-master-f3.png"),
    require("../../assets/formi/study-master-f4.png"),
    require("../../assets/formi/study-master-f5.png"),
    require("../../assets/formi/study-master-f6.png"),
    require("../../assets/formi/study-master-f7.png"),
  ],
  "study-sprout": [
    require("../../assets/formi/study-sprout-f0.png"),
    require("../../assets/formi/study-sprout-f1.png"),
    require("../../assets/formi/study-sprout-f2.png"),
    require("../../assets/formi/study-sprout-f3.png"),
  ],
} as const;
